# Generated by Django 4.1.7 on 2023-05-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_news', '0002_remove_news_author_news_status_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
    ]
