# Generated by Django 4.1.7 on 2023-05-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_news', '0003_news_verificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
